# Generated by Django 5.2.16 on 2026-07-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='codISBN', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titolo', max_length=255)),
                ('year', models.PositiveIntegerField(db_column='anno')),
            ],
            options={
                'db_table': 'Libri',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('number', models.PositiveIntegerField(db_column='numero', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titolo', max_length=255)),
                ('recipe_type', models.CharField(choices=[('antipasto', 'Antipasto'), ('primo', 'Primo'), ('secondo', 'Secondo'), ('contorno', 'Contorno'), ('dolce', 'Dolce')], db_column='tipo', max_length=50)),
                ('image', models.CharField(blank=True, db_column='immagine', max_length=255)),
            ],
            options={
                'db_table': 'Ricette',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(db_column='cod', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=100)),
                ('zone', models.CharField(db_column='zona', max_length=20)),
            ],
            options={
                'db_table': 'Regioni',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(db_column='idIngrediente', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ingrediente', max_length=255)),
                ('quantity', models.CharField(db_column='quantita', max_length=50)),
                ('number', models.PositiveIntegerField(db_column='numero')),
                ('recipe', models.ForeignKey(db_column='numeroRicetta', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cucina.recipe')),
            ],
            options={
                'db_table': 'Ingredienti',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(db_column='numeroPagina')),
                ('book', models.ForeignKey(db_column='libro', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='cucina.book')),
                ('recipe', models.ForeignKey(db_column='numeroRicetta', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='cucina.recipe')),
            ],
            options={
                'db_table': 'Pagine',
                'ordering': ['page_number'],
                'constraints': [models.UniqueConstraint(fields=('book', 'page_number'), name='unique_book_page')],
            },
        ),
        migrations.CreateModel(
            name='RegionalRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(db_column='numeroRicetta', on_delete=django.db.models.deletion.CASCADE, related_name='regional_links', to='cucina.recipe')),
                ('region', models.ForeignKey(db_column='cod', on_delete=django.db.models.deletion.CASCADE, related_name='regional_recipes', to='cucina.region')),
            ],
            options={
                'db_table': 'RicettaRegionale',
                'constraints': [models.UniqueConstraint(fields=('region', 'recipe'), name='unique_region_recipe')],
            },
        ),
    ]
