INSERT INTO Regioni (cod, nome, zona) VALUES
('ABR','Abruzzo','Sud'),
('BAS','Basilicata','Sud'),
('CAL','Calabria','Sud'),
('CAM','Campania','Sud'),
('EMR','Emilia-Romagna','Nord'),
('FVG','Friuli-Venezia Giulia','Nord'),
('LAZ','Lazio','Centro'),
('LIG','Liguria','Nord'),
('LOM','Lombardia','Nord'),
('MAR','Marche','Centro'),
('MOL','Molise','Sud'),
('PIE','Piemonte','Nord'),
('PUG','Puglia','Sud'),
('SAR','Sardegna','Isole'),
('SIC','Sicilia','Isole'),
('TOS','Toscana','Centro'),
('TAA','Trentino-Alto Adige','Nord'),
('UMB','Umbria','Centro'),
('VDA','Valle d''Aosta','Nord'),
('VEN','Veneto','Nord');
