INSERT INTO Ricette (numero, titolo, tipo, immagine) VALUES
(1,'Pallotte cacio e ova','secondo','illustrazione_001_pallotte_cacio_e_ova_v3.svg'),
(2,'Scrippelle mbusse','primo','illustrazione_002_scrippelle_mbusse_v3.svg'),
(3,'Timballo alla teramana','primo','illustrazione_003_timballo_alla_teramana_v3.svg'),
(4,'Arrosticini abruzzesi','secondo','illustrazione_004_arrosticini_abruzzesi_v3.svg'),
(5,'Virtù teramane','primo','illustrazione_005_virtu_teramane_v3.svg'),
(6,'Maccheroni alla chitarra','primo','illustrazione_006_maccheroni_alla_chitarra_v3.svg'),
(7,'Agnello cacio e uova','secondo','illustrazione_007_agnello_cacio_e_uova_v3.svg'),
(8,'Fiadoni salati','antipasto','illustrazione_008_fiadoni_salati_v3.svg'),
(9,'Pizza dogge abruzzese','dolce','illustrazione_009_pizza_dogge_abruzzese_v3.svg'),
(10,'Parrozzo','dolce','illustrazione_010_parrozzo_v3.svg'),
(11,'Ferratelle','dolce','illustrazione_011_ferratelle_v3.svg'),
(12,'Cicerchiata abruzzese','dolce','illustrazione_012_cicerchiata_abruzzese_v3.svg'),
(13,'Baccalà all’abruzzese','secondo','illustrazione_013_baccala_allabruzzese_v3.svg'),
(14,'Patate maritate','contorno','illustrazione_014_patate_maritate_v3.svg'),
(15,'Pizzelle fritte abruzzesi','antipasto','illustrazione_015_pizzelle_fritte_abruzzesi_v3.svg'),
(16,'Crapiata materana','primo','foto_016_crapiata_materana_v3.jpg'),
(17,'Strazzata lucana','antipasto','illustrazione_017_strazzata_lucana_v3.svg'),
(18,'Lagane e ceci','primo','illustrazione_018_lagane_e_ceci_v3.svg'),
(19,'Peperoni cruschi','contorno','illustrazione_019_peperoni_cruschi_v3.svg'),
(20,'Baccalà alla lucana','secondo','illustrazione_020_baccala_alla_lucana_v3.svg'),
(21,'Agnello alla contadina','secondo','illustrazione_021_agnello_alla_contadina_v3.svg'),
(22,'Rafanata','secondo','illustrazione_022_rafanata_v3.svg'),
(23,'Calzone di cipolla lucano','antipasto','illustrazione_023_calzone_di_cipolla_lucano_v3.svg'),
(24,'Fusilli con mollica e peperoni','primo','illustrazione_024_fusilli_con_mollica_e_peperoni_v3.svg'),
(25,'Cutturiddi','secondo','illustrazione_025_cutturiddi_v3.svg'),
(26,'Ciambotta lucana','contorno','illustrazione_026_ciambotta_lucana_v3.svg'),
(27,'Pasticcio di patate materano','secondo','illustrazione_027_pasticcio_di_patate_materano_v3.svg'),
(28,'Sospiri lucani','dolce','illustrazione_028_sospiri_lucani_v3.svg'),
(29,'Scorzette di Bernalda','dolce','illustrazione_029_scorzette_di_bernalda_v3.svg'),
(30,'Taralli aviglianesi','antipasto','illustrazione_030_taralli_aviglianesi_v3.svg'),
(31,'Fileja alla nduja','primo','foto_031_fileja_alla_nduja_v3.jpg'),
(32,'Morzeddhu catanzarese','secondo','illustrazione_032_morzeddhu_catanzarese_v3.svg'),
(33,'Pasta con patate alla cosentina','primo','illustrazione_033_pasta_con_patate_alla_cosentina_v3.svg'),
(34,'Melanzane ripiene calabresi','secondo','illustrazione_034_melanzane_ripiene_calabresi_v3.svg'),
(35,'Frittelle di fiori di zucca','antipasto','illustrazione_035_frittelle_di_fiori_di_zucca_v3.svg'),
(36,'Pesce spada alla ghiotta','secondo','illustrazione_036_pesce_spada_alla_ghiotta_v3.svg'),
(37,'Patate mpacchiuse','contorno','illustrazione_037_patate_mpacchiuse_v3.svg'),
(38,'Sardella calabrese','antipasto','illustrazione_038_sardella_calabrese_v3.svg'),
(39,'Lagane e cicciari','primo','illustrazione_039_lagane_e_cicciari_v3.svg'),
(40,'Pitta calabrese','antipasto','illustrazione_040_pitta_calabrese_v3.svg'),
(41,'Cuzzupe','dolce','illustrazione_041_cuzzupe_v3.svg'),
(42,'Turdilli','dolce','illustrazione_042_turdilli_v3.svg'),
(43,'Mostaccioli calabresi','dolce','illustrazione_043_mostaccioli_calabresi_v3.svg'),
(44,'Stocco alla mammolese','secondo','illustrazione_044_stocco_alla_mammolese_v3.svg'),
(45,'Zuppa di cipolle di Tropea','primo','illustrazione_045_zuppa_di_cipolle_di_tropea_v3.svg'),
(46,'Pizza napoletana','secondo','foto_046_pizza_napoletana_v3.jpg'),
(47,'Genovese napoletana','primo','illustrazione_047_genovese_napoletana_v3.svg'),
(48,'Pasta e patate con provola','primo','illustrazione_048_pasta_e_patate_con_provola_v3.svg'),
(49,'Gnocchi alla sorrentina','primo','foto_049_gnocchi_alla_sorrentina_v3.jpg'),
(50,'Parmigiana di melanzane','secondo','foto_050_parmigiana_di_melanzane_v3.jpg'),
(51,'Sartù di riso','primo','illustrazione_051_sartu_di_riso_v3.svg'),
(52,'Casatiello napoletano','antipasto','illustrazione_052_casatiello_napoletano_v3.svg'),
(53,'Gattò di patate','secondo','illustrazione_053_gatto_di_patate_v3.svg'),
(54,'Polpo alla luciana','secondo','illustrazione_054_polpo_alla_luciana_v3.svg'),
(55,'Cuoppo di mare','antipasto','illustrazione_055_cuoppo_di_mare_v3.svg'),
(56,'Pastiera napoletana','dolce','illustrazione_056_pastiera_napoletana_v3.svg'),
(57,'Sfogliatella riccia','dolce','illustrazione_057_sfogliatella_riccia_v3.svg'),
(58,'Babà al rum','dolce','foto_058_baba_al_rum_v3.jpg'),
(59,'Zeppole di San Giuseppe','dolce','foto_059_zeppole_di_san_giuseppe_v3.jpg'),
(60,'Scarpariello','primo','illustrazione_060_scarpariello_v3.svg'),
(61,'Lasagne alla bolognese','primo','foto_061_lasagne_alla_bolognese_v3.jpg'),
(62,'Tortellini in brodo','primo','foto_062_tortellini_in_brodo_v3.jpg'),
(63,'Tagliatelle al ragù','primo','foto_063_tagliatelle_al_ragu_v3.jpg'),
(64,'Cappelletti romagnoli','primo','illustrazione_064_cappelletti_romagnoli_v3.svg'),
(65,'Passatelli in brodo','primo','illustrazione_065_passatelli_in_brodo_v3.svg'),
(66,'Erbazzone reggiano','antipasto','illustrazione_066_erbazzone_reggiano_v3.svg'),
(67,'Gnocco fritto','antipasto','illustrazione_067_gnocco_fritto_v3.svg'),
(68,'Crescentine modenesi','antipasto','illustrazione_068_crescentine_modenesi_v3.svg'),
(69,'Cotoletta alla bolognese','secondo','illustrazione_069_cotoletta_alla_bolognese_v3.svg'),
(70,'Friggione bolognese','contorno','foto_070_friggione_bolognese_v3.jpg'),
(71,'Piadina romagnola','antipasto','illustrazione_071_piadina_romagnola_v3.svg'),
(72,'Torta tenerina','dolce','illustrazione_072_torta_tenerina_v3.svg'),
(73,'Zuppa inglese emiliana','dolce','illustrazione_073_zuppa_inglese_emiliana_v3.svg'),
(74,'Ciambella romagnola','dolce','illustrazione_074_ciambella_romagnola_v3.svg'),
(75,'Anolini di Parma','primo','illustrazione_075_anolini_di_parma_v3.svg'),
(76,'Frico friulano','secondo','foto_076_frico_friulano_v3.jpg'),
(77,'Jota triestina','primo','illustrazione_077_jota_triestina_v3.svg'),
(78,'Cjarsons','primo','illustrazione_078_cjarsons_v3.svg'),
(79,'Brovada e muset','secondo','illustrazione_079_brovada_e_muset_v3.svg'),
(80,'Gulasch triestino','secondo','illustrazione_080_gulasch_triestino_v3.svg'),
(81,'Blecs friulani','primo','illustrazione_081_blecs_friulani_v3.svg'),
(82,'Orzotto con erbe','primo','illustrazione_082_orzotto_con_erbe_v3.svg'),
(83,'Polenta pasticciata friulana','primo','illustrazione_083_polenta_pasticciata_friulana_v3.svg'),
(84,'Sardoni impanati','secondo','illustrazione_084_sardoni_impanati_v3.svg'),
(85,'Patate in tecia','contorno','illustrazione_085_patate_in_tecia_v3.svg'),
(86,'Presnitz triestino','dolce','illustrazione_086_presnitz_triestino_v3.svg'),
(87,'Gubana friulana','dolce','illustrazione_087_gubana_friulana_v3.svg'),
(88,'Strucchi','dolce','illustrazione_088_strucchi_v3.svg'),
(89,'Pinza triestina','dolce','illustrazione_089_pinza_triestina_v3.svg'),
(90,'Scampi alla busara','secondo','illustrazione_090_scampi_alla_busara_v3.svg'),
(91,'Cacio e pepe','primo','foto_091_cacio_e_pepe_v3.jpg'),
(92,'Spaghetti alla carbonara','primo','foto_092_spaghetti_alla_carbonara_v3.jpg'),
(93,'Bucatini all’amatriciana','primo','illustrazione_093_bucatini_allamatriciana_v3.svg'),
(94,'Gricia','primo','illustrazione_094_gricia_v3.svg'),
(95,'Saltimbocca alla romana','secondo','foto_095_saltimbocca_alla_romana_v3.jpg'),
(96,'Coda alla vaccinara','secondo','illustrazione_096_coda_alla_vaccinara_v3.svg'),
(97,'Trippa alla romana','secondo','foto_097_trippa_alla_romana_v3.jpg'),
(98,'Abbacchio alla scottadito','secondo','illustrazione_098_abbacchio_alla_scottadito_v3.svg'),
(99,'Carciofi alla romana','contorno','foto_099_carciofi_alla_romana_v3.jpg'),
(100,'Carciofi alla giudia','contorno','illustrazione_100_carciofi_alla_giudia_v3.svg'),
(101,'Supplì al telefono','antipasto','illustrazione_101_suppli_al_telefono_v3.svg'),
(102,'Maritozzi con panna','dolce','illustrazione_102_maritozzi_con_panna_v3.svg'),
(103,'Crostata di ricotta e visciole','dolce','illustrazione_103_crostata_di_ricotta_e_visciole_v3.svg'),
(104,'Pangiallo romano','dolce','illustrazione_104_pangiallo_romano_v3.svg'),
(105,'Pasta e ceci alla romana','primo','illustrazione_105_pasta_e_ceci_alla_romana_v3.svg'),
(106,'Focaccia genovese','antipasto','foto_106_focaccia_genovese_v3.jpg'),
(107,'Trofie al pesto','primo','foto_107_trofie_al_pesto_v3.jpg'),
(108,'Pansoti con salsa di noci','primo','illustrazione_108_pansoti_con_salsa_di_noci_v3.svg'),
(109,'Minestrone alla genovese','primo','foto_109_minestrone_alla_genovese_v3.jpg'),
(110,'Coniglio alla ligure','secondo','foto_110_coniglio_alla_ligure_v3.jpg'),
(111,'Cima alla genovese','secondo','illustrazione_111_cima_alla_genovese_v3.svg'),
(112,'Farinata di ceci','antipasto','illustrazione_112_farinata_di_ceci_v3.svg'),
(113,'Torta pasqualina','antipasto','illustrazione_113_torta_pasqualina_v3.svg'),
(114,'Acciughe ripiene','secondo','illustrazione_114_acciughe_ripiene_v3.svg'),
(115,'Brandacujun','secondo','illustrazione_115_brandacujun_v3.svg'),
(116,'Cappon magro','secondo','illustrazione_116_cappon_magro_v3.svg'),
(117,'Baci di Alassio','dolce','illustrazione_117_baci_di_alassio_v3.svg'),
(118,'Canestrelli liguri','dolce','illustrazione_118_canestrelli_liguri_v3.svg'),
(119,'Pandolce genovese','dolce','illustrazione_119_pandolce_genovese_v3.svg'),
(120,'Mesciua spezzina','primo','illustrazione_120_mesciua_spezzina_v3.svg'),
(121,'Risotto alla milanese','primo','foto_121_risotto_alla_milanese_v3.jpg'),
(122,'Cotoletta alla milanese','secondo','foto_122_cotoletta_alla_milanese_v3.jpg'),
(123,'Ossobuco alla milanese','secondo','foto_123_ossobuco_alla_milanese_v3.jpg'),
(124,'Pizzoccheri della Valtellina','primo','foto_124_pizzoccheri_della_valtellina_v3.jpg'),
(125,'Casoncelli bergamaschi','primo','illustrazione_125_casoncelli_bergamaschi_v3.svg'),
(126,'Polenta taragna','primo','illustrazione_126_polenta_taragna_v3.svg'),
(127,'Mondeghili','secondo','illustrazione_127_mondeghili_v3.svg'),
(128,'Cassoeula','secondo','illustrazione_128_cassoeula_v3.svg'),
(129,'Risotto con pesce persico','primo','illustrazione_129_risotto_con_pesce_persico_v3.svg'),
(130,'Sciatt valtellinesi','antipasto','illustrazione_130_sciatt_valtellinesi_v3.svg'),
(131,'Torta sbrisolona','dolce','illustrazione_131_torta_sbrisolona_v3.svg'),
(132,'Panettone milanese','dolce','illustrazione_132_panettone_milanese_v3.svg'),
(133,'Torrone di Cremona','dolce','illustrazione_133_torrone_di_cremona_v3.svg'),
(134,'Torta paradiso','dolce','illustrazione_134_torta_paradiso_v3.svg'),
(135,'Riso al salto','primo','illustrazione_135_riso_al_salto_v3.svg'),
(136,'Olive all’ascolana','antipasto','illustrazione_136_olive_allascolana_v3.svg'),
(137,'Vincisgrassi','primo','illustrazione_137_vincisgrassi_v3.svg'),
(138,'Brodetto all’anconetana','secondo','illustrazione_138_brodetto_allanconetana_v3.svg'),
(139,'Crescia sfogliata','antipasto','illustrazione_139_crescia_sfogliata_v3.svg'),
(140,'Coniglio in porchetta','secondo','illustrazione_140_coniglio_in_porchetta_v3.svg'),
(141,'Stoccafisso all’anconetana','secondo','illustrazione_141_stoccafisso_allanconetana_v3.svg'),
(142,'Maccheroncini di Campofilone','primo','illustrazione_142_maccheroncini_di_campofilone_v3.svg'),
(143,'Passatelli asciutti','primo','illustrazione_143_passatelli_asciutti_v3.svg'),
(144,'Cicerchiata marchigiana','dolce','illustrazione_144_cicerchiata_marchigiana_v3.svg'),
(145,'Calcioni marchigiani','dolce','illustrazione_145_calcioni_marchigiani_v3.svg'),
(146,'Ciambellone marchigiano','dolce','illustrazione_146_ciambellone_marchigiano_v3.svg'),
(147,'Frittelle di polenta','antipasto','illustrazione_147_frittelle_di_polenta_v3.svg'),
(148,'Seppie con piselli','secondo','illustrazione_148_seppie_con_piselli_v3.svg'),
(149,'Fave in porchetta','contorno','illustrazione_149_fave_in_porchetta_v3.svg'),
(150,'Zuppa di ceci e castagne','primo','illustrazione_150_zuppa_di_ceci_e_castagne_v3.svg'),
(151,'Cavatelli al ragù molisano','primo','illustrazione_151_cavatelli_al_ragu_molisano_v3.svg'),
(152,'Pampanella molisana','secondo','illustrazione_152_pampanella_molisana_v3.svg'),
(153,'Pizza e minestra','primo','illustrazione_153_pizza_e_minestra_v3.svg'),
(154,'Fusilli alla molisana','primo','illustrazione_154_fusilli_alla_molisana_v3.svg'),
(155,'Brodetto di Termoli','secondo','illustrazione_155_brodetto_di_termoli_v3.svg'),
(156,'Agnello alla molisana','secondo','illustrazione_156_agnello_alla_molisana_v3.svg'),
(157,'Baccalà arracanato','secondo','illustrazione_157_baccala_arracanato_v3.svg'),
(158,'Pezzata','secondo','illustrazione_158_pezzata_v3.svg'),
(159,'Frittata con cipolle','secondo','illustrazione_159_frittata_con_cipolle_v3.svg'),
(160,'Calcioni molisani','antipasto','illustrazione_160_calcioni_molisani_v3.svg'),
(161,'Cauciuni','dolce','illustrazione_161_cauciuni_v3.svg'),
(162,'Mostaccioli molisani','dolce','illustrazione_162_mostaccioli_molisani_v3.svg'),
(163,'Pigna pasquale','dolce','illustrazione_163_pigna_pasquale_v3.svg'),
(164,'Torcinelli molisani','secondo','illustrazione_164_torcinelli_molisani_v3.svg'),
(165,'Zuppa di farro molisana','primo','illustrazione_165_zuppa_di_farro_molisana_v3.svg'),
(166,'Bagna cauda','antipasto','foto_166_bagna_cauda_v3.jpg'),
(167,'Agnolotti del plin','primo','illustrazione_167_agnolotti_del_plin_v3.svg'),
(168,'Vitello tonnato','antipasto','illustrazione_168_vitello_tonnato_v3.svg'),
(169,'Brasato al Barolo','secondo','foto_169_brasato_al_barolo_v3.jpg'),
(170,'Bollito misto piemontese','secondo','foto_170_bollito_misto_piemontese_v3.jpg'),
(171,'Tajarin al ragù','primo','illustrazione_171_tajarin_al_ragu_v3.svg'),
(172,'Panissa vercellese','primo','illustrazione_172_panissa_vercellese_v3.svg'),
(173,'Finanziera piemontese','secondo','illustrazione_173_finanziera_piemontese_v3.svg'),
(174,'Fritto misto piemontese','secondo','illustrazione_174_fritto_misto_piemontese_v3.svg'),
(175,'Tonno di coniglio','antipasto','illustrazione_175_tonno_di_coniglio_v3.svg'),
(176,'Bonet piemontese','dolce','foto_176_bonet_piemontese_v3.jpg'),
(177,'Baci di dama','dolce','illustrazione_177_baci_di_dama_v3.svg'),
(178,'Paste di meliga','dolce','illustrazione_178_paste_di_meliga_v3.svg'),
(179,'Panna cotta','dolce','foto_179_panna_cotta_v3.jpg'),
(180,'Risotto al Barolo','primo','illustrazione_180_risotto_al_barolo_v3.svg'),
(181,'Orecchiette alle cime di rapa','primo','foto_181_orecchiette_alle_cime_di_rapa_v3.jpg'),
(182,'Tiella barese','primo','illustrazione_182_tiella_barese_v3.svg'),
(183,'Focaccia barese','antipasto','illustrazione_183_focaccia_barese_v3.svg'),
(184,'Bombette pugliesi','secondo','illustrazione_184_bombette_pugliesi_v3.svg'),
(185,'Ciceri e tria','primo','illustrazione_185_ciceri_e_tria_v3.svg'),
(186,'Riso patate e cozze','primo','illustrazione_186_riso_patate_e_cozze_v3.svg'),
(187,'Fave e cicoria','contorno','illustrazione_187_fave_e_cicoria_v3.svg'),
(188,'Panzerotti pugliesi','antipasto','illustrazione_188_panzerotti_pugliesi_v3.svg'),
(189,'Polpo alla pignata','secondo','illustrazione_189_polpo_alla_pignata_v3.svg'),
(190,'Acquasale pugliese','antipasto','illustrazione_190_acquasale_pugliese_v3.svg'),
(191,'Cartellate','dolce','illustrazione_191_cartellate_v3.svg'),
(192,'Pasticciotto leccese','dolce','illustrazione_192_pasticciotto_leccese_v3.svg'),
(193,'Sporcamuss','dolce','illustrazione_193_sporcamuss_v3.svg'),
(194,'Pettole pugliesi','antipasto','illustrazione_194_pettole_pugliesi_v3.svg'),
(195,'Melanzane ripiene pugliesi','secondo','illustrazione_195_melanzane_ripiene_pugliesi_v3.svg'),
(196,'Porceddu arrosto','secondo','foto_196_porceddu_arrosto_v3.jpg'),
(197,'Culurgiones ogliastrini','primo','illustrazione_197_culurgiones_ogliastrini_v3.svg'),
(198,'Malloreddus alla campidanese','primo','illustrazione_198_malloreddus_alla_campidanese_v3.svg'),
(199,'Fregola con arselle','primo','illustrazione_199_fregola_con_arselle_v3.svg'),
(200,'Zuppa gallurese','primo','illustrazione_200_zuppa_gallurese_v3.svg'),
(201,'Pane frattau','primo','illustrazione_201_pane_frattau_v3.svg'),
(202,'Seadas','dolce','illustrazione_202_seadas_v3.svg'),
(203,'Pardulas','dolce','illustrazione_203_pardulas_v3.svg'),
(204,'Amaretti sardi','dolce','illustrazione_204_amaretti_sardi_v3.svg'),
(205,'Burrida cagliaritana','secondo','illustrazione_205_burrida_cagliaritana_v3.svg'),
(206,'Agnello con carciofi','secondo','illustrazione_206_agnello_con_carciofi_v3.svg'),
(207,'Panadas sarde','antipasto','illustrazione_207_panadas_sarde_v3.svg'),
(208,'Coccoi prena','antipasto','illustrazione_208_coccoi_prena_v3.svg'),
(209,'Polpo alla carlofortina','secondo','illustrazione_209_polpo_alla_carlofortina_v3.svg'),
(210,'Minestra di fregola','primo','illustrazione_210_minestra_di_fregola_v3.svg'),
(211,'Arancini siciliani','antipasto','foto_211_arancini_siciliani_v3.jpg'),
(212,'Pasta alla Norma','primo','foto_212_pasta_alla_norma_v3.jpg'),
(213,'Caponata siciliana','contorno','foto_213_caponata_siciliana_v3.jpg'),
(214,'Pasta con le sarde','primo','illustrazione_214_pasta_con_le_sarde_v3.svg'),
(215,'Anelletti al forno','primo','illustrazione_215_anelletti_al_forno_v3.svg'),
(216,'Involtini di pesce spada','secondo','illustrazione_216_involtini_di_pesce_spada_v3.svg'),
(217,'Sarde a beccafico','secondo','illustrazione_217_sarde_a_beccafico_v3.svg'),
(218,'Panelle palermitane','antipasto','illustrazione_218_panelle_palermitane_v3.svg'),
(219,'Sfincione palermitano','antipasto','illustrazione_219_sfincione_palermitano_v3.svg'),
(220,'Cous cous trapanese','primo','illustrazione_220_cous_cous_trapanese_v3.svg'),
(221,'Cannoli siciliani','dolce','foto_221_cannoli_siciliani_v3.jpg'),
(222,'Cassata siciliana','dolce','illustrazione_222_cassata_siciliana_v3.svg'),
(223,'Granita alla mandorla','dolce','illustrazione_223_granita_alla_mandorla_v3.svg'),
(224,'Buccellati siciliani','dolce','illustrazione_224_buccellati_siciliani_v3.svg'),
(225,'Pignolata messinese','dolce','illustrazione_225_pignolata_messinese_v3.svg'),
(226,'Pappa al pomodoro','primo','foto_226_pappa_al_pomodoro_v3.jpg'),
(227,'Ribollita toscana','primo','foto_227_ribollita_toscana_v3.jpg'),
(228,'Bistecca alla fiorentina','secondo','foto_228_bistecca_alla_fiorentina_v3.jpg'),
(229,'Panzanella toscana','contorno','foto_229_panzanella_toscana_v3.jpg'),
(230,'Cacciucco livornese','secondo','illustrazione_230_cacciucco_livornese_v3.svg'),
(231,'Peposo all’imprunetina','secondo','illustrazione_231_peposo_allimprunetina_v3.svg'),
(232,'Lampredotto','secondo','illustrazione_232_lampredotto_v3.svg'),
(233,'Crostini toscani','antipasto','illustrazione_233_crostini_toscani_v3.svg'),
(234,'Acquacotta maremmana','primo','illustrazione_234_acquacotta_maremmana_v3.svg'),
(235,'Gnudi ricotta e spinaci','primo','illustrazione_235_gnudi_ricotta_e_spinaci_v3.svg'),
(236,'Cantucci toscani','dolce','illustrazione_236_cantucci_toscani_v3.svg'),
(237,'Castagnaccio','dolce','illustrazione_237_castagnaccio_v3.svg'),
(238,'Schiacciata all’uva','dolce','illustrazione_238_schiacciata_alluva_v3.svg'),
(239,'Torta co’ bischeri','dolce','illustrazione_239_torta_co_bischeri_v3.svg'),
(240,'Fagioli all’uccelletto','contorno','illustrazione_240_fagioli_alluccelletto_v3.svg'),
(241,'Canederli allo speck','primo','foto_241_canederli_allo_speck_v3.jpg'),
(242,'Spätzle agli spinaci','primo','illustrazione_242_spatzle_agli_spinaci_v3.svg'),
(243,'Strangolapreti trentini','primo','illustrazione_243_strangolapreti_trentini_v3.svg'),
(244,'Gulasch sudtirolese','secondo','illustrazione_244_gulasch_sudtirolese_v3.svg'),
(245,'Carne salada e fasoi','secondo','illustrazione_245_carne_salada_e_fasoi_v3.svg'),
(246,'Tortel di patate','contorno','illustrazione_246_tortel_di_patate_v3.svg'),
(247,'Polenta di Storo','primo','illustrazione_247_polenta_di_storo_v3.svg'),
(248,'Zuppa d’orzo tirolese','primo','illustrazione_248_zuppa_dorzo_tirolese_v3.svg'),
(249,'Schlutzkrapfen','primo','illustrazione_249_schlutzkrapfen_v3.svg'),
(250,'Crauti alla tirolese','contorno','illustrazione_250_crauti_alla_tirolese_v3.svg'),
(251,'Strudel di mele','dolce','illustrazione_251_strudel_di_mele_v3.svg'),
(252,'Krapfen tirolesi','dolce','illustrazione_252_krapfen_tirolesi_v3.svg'),
(253,'Zelten trentino','dolce','illustrazione_253_zelten_trentino_v3.svg'),
(254,'Strauben','dolce','illustrazione_254_strauben_v3.svg'),
(255,'Torta di grano saraceno','dolce','illustrazione_255_torta_di_grano_saraceno_v3.svg'),
(256,'Torta al testo','antipasto','foto_256_torta_al_testo_v3.jpg'),
(257,'Strangozzi al tartufo','primo','illustrazione_257_strangozzi_al_tartufo_v3.svg'),
(258,'Pasta alla norcina','primo','illustrazione_258_pasta_alla_norcina_v3.svg'),
(259,'Palomba alla ghiotta','secondo','illustrazione_259_palomba_alla_ghiotta_v3.svg'),
(260,'Agnello scottadito umbro','secondo','illustrazione_260_agnello_scottadito_umbro_v3.svg'),
(261,'Friccò all’eugubina','secondo','illustrazione_261_fricco_alleugubina_v3.svg'),
(262,'Bandiera umbra','contorno','illustrazione_262_bandiera_umbra_v3.svg'),
(263,'Fagiolina del Trasimeno','contorno','illustrazione_263_fagiolina_del_trasimeno_v3.svg'),
(264,'Crescia di Gubbio','antipasto','illustrazione_264_crescia_di_gubbio_v3.svg'),
(265,'Rocciata umbra','dolce','illustrazione_265_rocciata_umbra_v3.svg'),
(266,'Torcolo di San Costanzo','dolce','illustrazione_266_torcolo_di_san_costanzo_v3.svg'),
(267,'Pinoccate perugine','dolce','illustrazione_267_pinoccate_perugine_v3.svg'),
(268,'Tozzetti umbri','dolce','illustrazione_268_tozzetti_umbri_v3.svg'),
(269,'Zuppa di lenticchie di Castelluccio','primo','illustrazione_269_zuppa_di_lenticchie_di_castelluccio_v3.svg'),
(270,'Cipollata umbra','primo','illustrazione_270_cipollata_umbra_v3.svg'),
(271,'Fonduta valdostana','antipasto','foto_271_fonduta_valdostana_v3.jpg'),
(272,'Polenta concia valdostana','primo','foto_272_polenta_concia_valdostana_v3.jpg'),
(273,'Carbonade valdostana','secondo','illustrazione_273_carbonade_valdostana_v3.svg'),
(274,'Cotoletta alla valdostana','secondo','illustrazione_274_cotoletta_alla_valdostana_v3.svg'),
(275,'Seupa à la vapelenentse','primo','illustrazione_275_seupa_a_la_vapelenentse_v3.svg'),
(276,'Crespelle alla valdostana','primo','illustrazione_276_crespelle_alla_valdostana_v3.svg'),
(277,'Gnocchi alla bava','primo','illustrazione_277_gnocchi_alla_bava_v3.svg'),
(278,'Trota alla valdostana','secondo','illustrazione_278_trota_alla_valdostana_v3.svg'),
(279,'Civet di camoscio','secondo','illustrazione_279_civet_di_camoscio_v3.svg'),
(280,'Tegole valdostane','dolce','illustrazione_280_tegole_valdostane_v3.svg'),
(281,'Fiandolein','dolce','illustrazione_281_fiandolein_v3.svg'),
(282,'Mecoulin di Cogne','dolce','illustrazione_282_mecoulin_di_cogne_v3.svg'),
(283,'Torta di pere e cioccolato','dolce','illustrazione_283_torta_di_pere_e_cioccolato_v3.svg'),
(284,'Frittelle di mele valdostane','dolce','illustrazione_284_frittelle_di_mele_valdostane_v3.svg'),
(285,'Zuppa di castagne valdostana','primo','illustrazione_285_zuppa_di_castagne_valdostana_v3.svg'),
(286,'Baccalà alla vicentina','secondo','foto_286_baccala_alla_vicentina_v3.jpg'),
(287,'Risi e bisi','primo','illustrazione_287_risi_e_bisi_v3.svg'),
(288,'Bigoli in salsa','primo','illustrazione_288_bigoli_in_salsa_v3.svg'),
(289,'Sarde in saor','antipasto','illustrazione_289_sarde_in_saor_v3.svg'),
(290,'Fegato alla veneziana','secondo','illustrazione_290_fegato_alla_veneziana_v3.svg'),
(291,'Pasta e fasoi veneta','primo','illustrazione_291_pasta_e_fasoi_veneta_v3.svg'),
(292,'Risotto al radicchio','primo','illustrazione_292_risotto_al_radicchio_v3.svg'),
(293,'Polenta e schie','secondo','illustrazione_293_polenta_e_schie_v3.svg'),
(294,'Seppie al nero','secondo','illustrazione_294_seppie_al_nero_v3.svg'),
(295,'Baccalà mantecato','antipasto','illustrazione_295_baccala_mantecato_v3.svg'),
(296,'Tiramisù','dolce','foto_296_tiramisu_v3.jpg'),
(297,'Pandoro veronese','dolce','illustrazione_297_pandoro_veronese_v3.svg'),
(298,'Zaleti veneziani','dolce','illustrazione_298_zaleti_veneziani_v3.svg'),
(299,'Fritole veneziane','dolce','illustrazione_299_fritole_veneziane_v3.svg'),
(300,'Pearà veronese','contorno','illustrazione_300_peara_veronese_v3.svg');
