INSERT INTO Ricette (numero, titolo, tipo, immagine) VALUES
(1,'Spaghetti alla chitarra','primo','Spaghetti_alla_chitarra.jpg'),
(2,'Crapiata materana','primo','Crapiata_materana.jpg'),
(3,'Fileja alla ''nduja','primo','Fileja_alla_nduja.jpg'),
(4,'Pizza napoletana','secondo','Pizza_napoletana.jpg'),
(5,'Lasagne alla bolognese','primo','Lasagne_alla_bolognese.jpg'),
(6,'Frico friulano','secondo','Frico_friulano.jpg'),
(7,'Cacio e pepe','primo','Cacio_e_pepe.jpg'),
(8,'Focaccia genovese','contorno','Focaccia_genovese.jpg'),
(9,'Risotto alla milanese','primo','Risotto_alla_milanese.jpg'),
(10,'Olive all''ascolana','antipasto','Olive_all_ascolana.jpg'),
(11,'Cavatelli molisani','primo','Cavatelli_molisani.jpg'),
(12,'Bagna cauda','antipasto','Bagna_cauda.jpg'),
(13,'Orecchiette alle cime di rapa','primo','Orecchiette_alle_cime_di_rapa.jpg'),
(14,'Porceddu arrosto','secondo','Porceddu_arrosto.jpg'),
(15,'Arancini siciliani','antipasto','Arancini_siciliani.jpg'),
(16,'Pappa al pomodoro','primo','Pappa_al_pomodoro.jpg'),
(17,'Canederli','primo','Canederli.jpg'),
(18,'Torta al testo','secondo','Torta_al_testo.jpg'),
(19,'Fonduta valdostana','antipasto','Fonduta_valdostana.jpg'),
(20,'Polenta e osei','secondo','Polenta_e_osei.jpg'),
(21,'Spaghetti alla carbonara','primo','Spaghetti_alla_carbonara.jpg'),
(22,'Tagliatelle al ragu','primo','Tagliatelle_al_ragu.jpg'),
(23,'Pasta alla Norma','primo','Pasta_alla_norma.jpg'),
(24,'Trofie al pesto genovese','primo','Trofie_al_pesto_genovese.jpg'),
(25,'Risotto ai funghi porcini','primo','Risotto_ai_funghi_porcini.jpg'),
(26,'Gnocchi alla sorrentina','primo','Gnocchi_alla_sorrentina.jpg'),
(27,'Pizzoccheri della Valtellina','primo','Pizzoccheri_della_valtellina.jpg'),
(28,'Minestrone alla genovese','primo','Minestrone_alla_genovese.jpg'),
(29,'Ribollita toscana','primo','Ribollita_toscana.jpg'),
(30,'Pasta e fagioli','primo','Pasta_e_fagioli.jpg'),
(31,'Bucatini all''amatriciana','primo','Bucatini_all_amatriciana.jpg'),
(32,'Risotto alla pescatora','primo','Risotto_alla_pescatora.jpg'),
(33,'Tortellini in brodo','primo','Tortellini_in_brodo.jpg'),
(34,'Pasta alla genovese napoletana','primo','Pasta_alla_genovese_napoletana.jpg'),
(35,'Polenta concia','primo','Polenta_concia.jpg'),
(36,'Bistecca alla fiorentina','secondo','Bistecca_alla_fiorentina.jpg'),
(37,'Cotoletta alla milanese','secondo','Cotoletta_alla_milanese.jpg'),
(38,'Saltimbocca alla romana','secondo','Saltimbocca_alla_romana.jpg'),
(39,'Osso buco alla milanese','secondo','Osso_buco_alla_milanese.jpg'),
(40,'Brasato al Barolo','secondo','Brasato_al_barolo.jpg'),
(41,'Polpette al sugo','secondo','Polpette_al_sugo.jpg'),
(42,'Bollito misto piemontese','secondo','Bollito_misto_piemontese.jpg'),
(43,'Arista di maiale al forno','secondo','Arista_di_maiale_al_forno.jpg'),
(44,'Trippa alla romana','secondo','Trippa_alla_romana.jpg'),
(45,'Baccala alla vicentina','secondo','Baccala_alla_vicentina.jpg'),
(46,'Frittura di paranza','secondo','Frittura_di_paranza.jpg'),
(47,'Spiedini di carne','secondo','Spiedini_di_carne.jpg'),
(48,'Stracotto di manzo','secondo','Stracotto_di_manzo.jpg'),
(49,'Coniglio alla ligure','secondo','Coniglio_alla_ligure.jpg'),
(50,'Porchetta','secondo','Porchetta.jpg'),
(51,'Acqua pazza','secondo','Acqua_pazza.jpg'),
(52,'Cuoppo napoletano','secondo','Cuoppo_napoletano.jpg'),
(53,'Anguilla in umido','secondo','Anguilla_in_umido.jpg'),
(54,'Caponata siciliana','contorno','Caponata_siciliana.jpg'),
(55,'Parmigiana di melanzane','contorno','Parmigiana_di_melanzane.jpg'),
(56,'Carciofi alla romana','contorno','Carciofi_alla_romana.jpg'),
(57,'Peperonata','contorno','Peperonata.jpg'),
(58,'Fagiolini al pomodoro','contorno','Fagiolini_al_pomodoro.jpg'),
(59,'Insalata caprese','contorno','Insalata_caprese.jpg'),
(60,'Patate al forno','contorno','Patate_al_forno.jpg'),
(61,'Friggione bolognese','contorno','Friggione_bolognese.jpg'),
(62,'Verdure grigliate','contorno','Verdure_grigliate.jpg'),
(63,'Panzanella','contorno','Panzanella.jpg'),
(64,'Tiramisu','dolce','Tiramisu.jpg'),
(65,'Panna cotta','dolce','Panna_cotta.jpg'),
(66,'Cannoli siciliani','dolce','Cannoli_siciliani.jpg'),
(67,'Pandoro','dolce','Pandoro.jpg'),
(68,'Panettone','dolce','Panettone.jpg'),
(69,'Sbrisolona mantovana','dolce','Sbrisolona_mantovana.jpg'),
(70,'Torta caprese','dolce','Torta_caprese.jpg'),
(71,'Zeppole di San Giuseppe','dolce','Zeppole_di_san_giuseppe.jpg'),
(72,'Bonet piemontese','dolce','Bonet_piemontese.jpg'),
(73,'Sfogliatella napoletana','dolce','Sfogliatella_napoletana.jpg'),
(74,'Crostata di marmellata','dolce','Crostata_di_marmellata.jpg'),
(75,'Babà al rum','dolce','Baba_al_rum.jpg');