INSERT INTO Ricette (numero, titolo, tipo, immagine) VALUES
(1,'Pallotte cacio e ova','secondo','001_pallotte_cacio_e_ova.jpg'),
(2,'Scrippelle mbusse','primo','002_scrippelle_mbusse.jpg'),
(3,'Timballo alla teramana','primo','003_timballo_alla_teramana.jpg'),
(4,'Arrosticini abruzzesi','secondo','004_arrosticini_abruzzesi.jpg'),
(5,'Virtù teramane','primo','005_virtu_teramane.jpg'),
(6,'Maccheroni alla chitarra','primo','006_maccheroni_alla_chitarra.jpg'),
(7,'Agnello cacio e uova','secondo','007_agnello_cacio_e_uova.jpg'),
(8,'Fiadoni salati','antipasto','008_fiadoni_salati.jpg'),
(9,'Pizza dogge abruzzese','dolce','009_pizza_dogge_abruzzese.jpg'),
(10,'Parrozzo','dolce','010_parrozzo.jpg'),
(11,'Ferratelle','dolce','011_ferratelle.jpg'),
(12,'Cicerchiata abruzzese','dolce','012_cicerchiata_abruzzese.jpg'),
(13,'Baccalà all’abruzzese','secondo','013_baccala_allabruzzese.jpg'),
(14,'Patate maritate','contorno','014_patate_maritate.jpg'),
(15,'Pizzelle fritte abruzzesi','antipasto','015_pizzelle_fritte_abruzzesi.jpg'),
(16,'Crapiata materana','primo','016_crapiata_materana.jpg'),
(17,'Strazzata lucana','antipasto','017_strazzata_lucana.jpg'),
(18,'Lagane e ceci','primo','018_lagane_e_ceci.jpg'),
(19,'Peperoni cruschi','contorno','019_peperoni_cruschi.jpg'),
(20,'Baccalà alla lucana','secondo','020_baccala_alla_lucana.jpg'),
(21,'Agnello alla contadina','secondo','021_agnello_alla_contadina.jpg'),
(22,'Rafanata','secondo','022_rafanata.jpg'),
(23,'Calzone di cipolla lucano','antipasto','023_calzone_di_cipolla_lucano.jpg'),
(24,'Fusilli con mollica e peperoni','primo','024_fusilli_con_mollica_e_peperoni.jpg'),
(25,'Cutturiddi','secondo','025_cutturiddi.jpg'),
(26,'Ciambotta lucana','contorno','026_ciambotta_lucana.jpg'),
(27,'Pasticcio di patate materano','secondo','027_pasticcio_di_patate_materano.jpg'),
(28,'Sospiri lucani','dolce','028_sospiri_lucani.jpg'),
(29,'Scorzette di Bernalda','dolce','029_scorzette_di_bernalda.jpg'),
(30,'Taralli aviglianesi','antipasto','030_taralli_aviglianesi.jpg'),
(31,'Fileja alla nduja','primo','031_fileja_alla_nduja.jpg'),
(32,'Morzeddhu catanzarese','secondo','032_morzeddhu_catanzarese.jpg'),
(33,'Pasta con patate alla cosentina','primo','033_pasta_con_patate_alla_cosentina.jpg'),
(34,'Melanzane ripiene calabresi','secondo','034_melanzane_ripiene_calabresi.jpg'),
(35,'Frittelle di fiori di zucca','antipasto','035_frittelle_di_fiori_di_zucca.jpg'),
(36,'Pesce spada alla ghiotta','secondo','036_pesce_spada_alla_ghiotta.jpg'),
(37,'Patate mpacchiuse','contorno','037_patate_mpacchiuse.jpg'),
(38,'Sardella calabrese','antipasto','038_sardella_calabrese.jpg'),
(39,'Lagane e cicciari','primo','039_lagane_e_cicciari.jpg'),
(40,'Pitta calabrese','antipasto','040_pitta_calabrese.jpg'),
(41,'Cuzzupe','dolce','041_cuzzupe.jpg'),
(42,'Turdilli','dolce','042_turdilli.jpg'),
(43,'Mostaccioli calabresi','dolce','043_mostaccioli_calabresi.jpg'),
(44,'Stocco alla mammolese','secondo','044_stocco_alla_mammolese.jpg'),
(45,'Zuppa di cipolle di Tropea','primo','045_zuppa_di_cipolle_di_tropea.jpg'),
(46,'Pizza napoletana','secondo','046_pizza_napoletana.jpg'),
(47,'Genovese napoletana','primo','047_genovese_napoletana.jpg'),
(48,'Pasta e patate con provola','primo','048_pasta_e_patate_con_provola.jpg'),
(49,'Gnocchi alla sorrentina','primo','049_gnocchi_alla_sorrentina.jpg'),
(50,'Parmigiana di melanzane','secondo','050_parmigiana_di_melanzane.jpg'),
(51,'Sartù di riso','primo','051_sartu_di_riso.jpgg'),
(52,'Casatiello napoletano','antipasto','052_casatiello_napoletano.jpg'),
(53,'Gattò di patate','secondo','053_gatto_di_patate.jpg'),
(54,'Polpo alla luciana','secondo','054_polpo_alla_luciana.jpg'),
(55,'Cuoppo di mare','antipasto','055_cuoppo_di_mare.jpg'),
(56,'Pastiera napoletana','dolce','056_pastiera_napoletana.jpg'),
(57,'Sfogliatella riccia','dolce','057_sfogliatella_riccia.jpg'),
(58,'Babà al rum','dolce','058_baba_al_rum.jpg'),
(59,'Zeppole di San Giuseppe','dolce','059_zeppole_di_san_giuseppe.jpg'),
(60,'Scarpariello','primo','060_scarpariello.jpg'),
(61,'Lasagne alla bolognese','primo','061_lasagne_alla_bolognese.jpg'),
(62,'Tortellini in brodo','primo','062_tortellini_in_brodo.jpg'),
(63,'Tagliatelle al ragù','primo','063_tagliatelle_al_ragu.jpg'),
(64,'Cappelletti romagnoli','primo','064_cappelletti_romagnoli.jpg'),
(65,'Passatelli in brodo','primo','065_passatelli_in_brodo.jpg'),
(66,'Erbazzone reggiano','antipasto','066_erbazzone_reggiano.jpg'),
(67,'Gnocco fritto','antipasto','067_gnocco_fritto.jpg'),
(68,'Crescentine modenesi','antipasto','068_crescentine_modenesi.jpg'),
(69,'Cotoletta alla bolognese','secondo','069_cotoletta_alla_bolognese.jpg'),
(70,'Friggione bolognese','contorno','070_friggione_bolognese.jpg'),
(71,'Piadina romagnola','antipasto','071_piadina_romagnola.jpg'),
(72,'Torta tenerina','dolce','072_torta_tenerina.jpg'),
(73,'Zuppa inglese emiliana','dolce','073_zuppa_inglese_emiliana.jpg'),
(74,'Ciambella romagnola','dolce','074_ciambella_romagnola.jpg'),
(75,'Anolini di Parma','primo','075_anolini_di_parma.jpg'),
(76,'Frico friulano','secondo','076_frico_friulano.jpg'),
(77,'Jota triestina','primo','077_jota_triestina.jpg'),
(78,'Cjarsons','primo','078_cjarsons.jpg'),
(79,'Brovada e muset','secondo','079_brovada_e_muset.jpg'),
(80,'Gulasch triestino','secondo','080_gulasch_triestino.jpg'),
(81,'Blecs friulani','primo','081_blecs_friulani.jpg'),
(82,'Orzotto con erbe','primo','082_orzotto_con_erbe.jpg'),
(83,'Polenta pasticciata friulana','primo','083_polenta_pasticciata_friulana.jpg'),
(84,'Sardoni impanati','secondo','084_sardoni_impanati.jpg'),
(85,'Patate in tecia','contorno','085_patate_in_tecia.jpg'),
(86,'Presnitz triestino','dolce','086_presnitz_triestino.jpg'),
(87,'Gubana friulana','dolce','087_gubana_friulana.jpg'),
(88,'Strucchi','dolce','088_strucchi.jpg'),
(89,'Pinza triestina','dolce','089_pinza_triestina.jpg'),
(90,'Scampi alla busara','secondo','090_scampi_alla_busara.jpg'),
(91,'Cacio e pepe','primo','091_cacio_e_pepe.jpg'),
(92,'Spaghetti alla carbonara','primo','092_spaghetti_alla_carbonara.jpg'),
(93,'Bucatini all’amatriciana','primo','093_bucatini_allamatriciana.jpg'),
(94,'Gricia','primo','094_gricia.jpg'),
(95,'Saltimbocca alla romana','secondo','095_saltimbocca_alla_romana.jpg'),
(96,'Coda alla vaccinara','secondo','096_coda_alla_vaccinara.jpg'),
(97,'Trippa alla romana','secondo','097_trippa_alla_romana.jpg'),
(98,'Abbacchio alla scottadito','secondo','098_abbacchio_alla_scottadito.jpg'),
(99,'Carciofi alla romana','contorno','099_carciofi_alla_romana.jpg'),
(100,'Carciofi alla giudia','contorno','100_carciofi_alla_giudia.jpg'),
(101,'Supplì al telefono','antipasto','101_suppli_al_telefono.jpg'),
(102,'Maritozzi con panna','dolce','102_maritozzi_con_panna.jpg'),
(103,'Crostata di ricotta e visciole','dolce','103_crostata_di_ricotta_e_visciole.jpg'),
(104,'Pangiallo romano','dolce','104_pangiallo_romano.jpg'),
(105,'Pasta e ceci alla romana','primo','105_pasta_e_ceci_alla_romana.jpg'),
(106,'Focaccia genovese','antipasto','106_focaccia_genovese.jpg'),
(107,'Trofie al pesto','primo','107_trofie_al_pesto.jpg'),
(108,'Pansoti con salsa di noci','primo','108_pansoti_con_salsa_di_noci.jpg'),
(109,'Minestrone alla genovese','primo','109_minestrone_alla_genovese.jpg'),
(110,'Coniglio alla ligure','secondo','110_coniglio_alla_ligure.jpg'),
(111,'Cima alla genovese','secondo','111_cima_alla_genovese.jpg'),
(112,'Farinata di ceci','antipasto','112_farinata_di_ceci.jpg'),
(113,'Torta pasqualina','antipasto','113_torta_pasqualina.jpg'),
(114,'Acciughe ripiene','secondo','114_acciughe_ripiene.jpg'),
(115,'Brandacujun','secondo','115_brandacujun.jpg'),
(116,'Cappon magro','secondo','116_cappon_magro.jpg'),
(117,'Baci di Alassio','dolce','117_baci_di_alassio.jpg'),
(118,'Canestrelli liguri','dolce','118_canestrelli_liguri.jpg'),
(119,'Pandolce genovese','dolce','119_pandolce_genovese.jpg'),
(120,'Mesciua spezzina','primo','120_mesciua_spezzina.jpg'),
(121,'Risotto alla milanese','primo','121_risotto_alla_milanese.jpg'),
(122,'Cotoletta alla milanese','secondo','122_cotoletta_alla_milanese.jpg'),
(123,'Ossobuco alla milanese','secondo','123_ossobuco_alla_milanese.jpg'),
(124,'Pizzoccheri della Valtellina','primo','124_pizzoccheri_della_valtellina.jpg'),
(125,'Casoncelli bergamaschi','primo','125_casoncelli_bergamaschi.jpg'),
(126,'Polenta taragna','primo','126_polenta_taragna.jpg'),
(127,'Mondeghili','secondo','127_mondeghili.jpg'),
(128,'Cassoeula','secondo','128_cassoeula.jpg'),
(129,'Risotto con pesce persico','primo','129_risotto_con_pesce_persico.jpg'),
(130,'Sciatt valtellinesi','antipasto','130_sciatt_valtellinesi.jpg'),
(131,'Torta sbrisolona','dolce','131_torta_sbrisolona.jpg'),
(132,'Panettone milanese','dolce','132_panettone_milanese.jpg'),
(133,'Torrone di Cremona','dolce','133_torrone_di_cremona.jpg'),
(134,'Torta paradiso','dolce','134_torta_paradiso.jpg'),
(135,'Riso al salto','primo','135_riso_al_salto.jpg'),
(136,'Olive all’ascolana','antipasto','136_olive_allascolana.jpg'),
(137,'Vincisgrassi','primo','137_vincisgrassi.jpg'),
(138,'Brodetto all’anconetana','secondo','138_brodetto_allanconetana.jpg'),
(139,'Crescia sfogliata','antipasto','139_crescia_sfogliata.jpg'),
(140,'Coniglio in porchetta','secondo','140_coniglio_in_porchetta.jpg'),
(141,'Stoccafisso all’anconetana','secondo','141_stoccafisso_allanconetana.jpg'),
(142,'Maccheroncini di Campofilone','primo','142_maccheroncini_di_campofilone.jpg'),
(143,'Passatelli asciutti','primo','143_passatelli_asciutti.jpg'),
(144,'Cicerchiata marchigiana','dolce','144_cicerchiata_marchigiana.jpg'),
(145,'Calcioni marchigiani','dolce','145_calcioni_marchigiani.jpg'),
(146,'Ciambellone marchigiano','dolce','146_ciambellone_marchigiano.jpg'),
(147,'Frittelle di polenta','antipasto','147_frittelle_di_polenta.jpg'),
(148,'Seppie con piselli','secondo','148_seppie_con_piselli.jpg'),
(149,'Fave in porchetta','contorno','149_fave_in_porchetta.jpg'),
(150,'Zuppa di ceci e castagne','primo','150_zuppa_di_ceci_e_castagne.jpg'),
(151,'Cavatelli al ragù molisano','primo','151_cavatelli_al_ragu_molisano.jpg'),
(152,'Pampanella molisana','secondo','152_pampanella_molisana.jpg'),
(153,'Pizza e minestra','primo','153_pizza_e_minestra.jpg'),
(154,'Fusilli alla molisana','primo','154_fusilli_alla_molisana.jpg'),
(155,'Brodetto di Termoli','secondo','155_brodetto_di_termoli.jpg'),
(156,'Agnello alla molisana','secondo','156_agnello_alla_molisana.jpg'),
(157,'Baccalà arracanato','secondo','157_baccala_arracanato.jpg'),
(158,'Pezzata','secondo','158_pezzata.jpg'),
(159,'Frittata con cipolle','secondo','159_frittata_con_cipolle.jpg'),
(160,'Calcioni molisani','antipasto','160_calcioni_molisani.jpg'),
(161,'Cauciuni','dolce','161_cauciuni.jpg'),
(162,'Mostaccioli molisani','dolce','162_mostaccioli_molisani.jpg'),
(163,'Pigna pasquale','dolce','163_pigna_pasquale.jpg'),
(164,'Torcinelli molisani','secondo','164_torcinelli_molisani.jpg'),
(165,'Zuppa di farro molisana','primo','165_zuppa_di_farro_molisana.jpg'),
(166,'Bagna cauda','antipasto','166_bagna_cauda.jpg'),
(167,'Agnolotti del plin','primo','167_agnolotti_del_plin.jpg'),
(168,'Vitello tonnato','antipasto','168_vitello_tonnato.jpg'),
(169,'Brasato al Barolo','secondo','169_brasato_al_barolo.jpg'),
(170,'Bollito misto piemontese','secondo','170_bollito_misto_piemontese.jpg'),
(171,'Tajarin al ragù','primo','171_tajarin_al_ragu.jpg'),
(172,'Panissa vercellese','primo','172_panissa_vercellese.jpg'),
(173,'Finanziera piemontese','secondo','173_finanziera_piemontese.jpg'),
(174,'Fritto misto piemontese','secondo','174_fritto_misto_piemontese.jpg'),
(175,'Tonno di coniglio','antipasto','175_tonno_di_coniglio.jpg'),
(176,'Bonet piemontese','dolce','176_bonet_piemontese.jpg'),
(177,'Baci di dama','dolce','177_baci_di_dama.jpg'),
(178,'Paste di meliga','dolce','178_paste_di_meliga.jpg'),
(179,'Panna cotta','dolce','179_panna_cotta.jpg'),
(180,'Risotto al Barolo','primo','180_risotto_al_barolo.jpg'),
(181,'Orecchiette alle cime di rapa','primo','181_orecchiette_alle_cime_di_rapa.jpg'),
(182,'Tiella barese','primo','182_tiella_barese.jpg'),
(183,'Focaccia barese','antipasto','183_focaccia_barese.jpg'),
(184,'Bombette pugliesi','secondo','184_bombette_pugliesi.jpg'),
(185,'Ciceri e tria','primo','185_ciceri_e_tria.jpg'),
(186,'Riso patate e cozze','primo','186_riso_patate_e_cozze.jpg'),
(187,'Fave e cicoria','contorno','187_fave_e_cicoria.jpg'),
(188,'Panzerotti pugliesi','antipasto','188_panzerotti_pugliesi.jpg'),
(189,'Polpo alla pignata','secondo','189_polpo_alla_pignata.jpg'),
(190,'Acquasale pugliese','antipasto','190_acquasale_pugliese.jpg'),
(191,'Cartellate','dolce','191_cartellate.jpg'),
(192,'Pasticciotto leccese','dolce','192_pasticciotto_leccese.jpg'),
(193,'Sporcamuss','dolce','193_sporcamuss.jpg'),
(194,'Pettole pugliesi','antipasto','194_pettole_pugliesi.jpg'),
(195,'Melanzane ripiene pugliesi','secondo','195_melanzane_ripiene_pugliesi.jpg'),
(196,'Porceddu arrosto','secondo','196_porceddu_arrosto.jpg'),
(197,'Culurgiones ogliastrini','primo','197_culurgiones_ogliastrini.jpg'),
(198,'Malloreddus alla campidanese','primo','198_malloreddus_alla_campidanese.jpg'),
(199,'Fregola con arselle','primo','199_fregola_con_arselle.jpg'),
(200,'Zuppa gallurese','primo','200_zuppa_gallurese.jpvg'),
(201,'Pane frattau','primo','201_pane_frattau.jpg'),
(202,'Seadas','dolce','202_seadas.jpg'),
(203,'Pardulas','dolce','203_pardulas.jpg'),
(204,'Amaretti sardi','dolce','204_amaretti_sardi.jpg'),
(205,'Burrida cagliaritana','secondo','205_burrida_cagliaritana.jpg'),
(206,'Agnello con carciofi','secondo','206_agnello_con_carciofi.jpg'),
(207,'Panadas sarde','antipasto','207_panadas_sarde.jpg'),
(208,'Coccoi prena','antipasto','208_coccoi_prena.jpg'),
(209,'Polpo alla carlofortina','secondo','209_polpo_alla_carlofortina.jpg'),
(210,'Minestra di fregola','primo','210_minestra_di_fregola.jpg'),
(211,'Arancini siciliani','antipasto','211_arancini_siciliani.jpg'),
(212,'Pasta alla Norma','primo','212_pasta_alla_norma.jpg'),
(213,'Caponata siciliana','contorno','213_caponata_siciliana.jpg'),
(214,'Pasta con le sarde','primo','214_pasta_con_le_sarde.jpg'),
(215,'Anelletti al forno','primo','215_anelletti_al_forno.jpg'),
(216,'Involtini di pesce spada','secondo','216_involtini_di_pesce_spada.jpg'),
(217,'Sarde a beccafico','secondo','217_sarde_a_beccafico.jpg'),
(218,'Panelle palermitane','antipasto','218_panelle_palermitane.jpg'),
(219,'Sfincione palermitano','antipasto','219_sfincione_palermitano.jpg'),
(220,'Cous cous trapanese','primo','220_cous_cous_trapanese.jpg'),
(221,'Cannoli siciliani','dolce','221_cannoli_siciliani.jpg'),
(222,'Cassata siciliana','dolce','222_cassata_siciliana.jpg'),
(223,'Granita alla mandorla','dolce','223_granita_alla_mandorla.jpg'),
(224,'Buccellati siciliani','dolce','224_buccellati_siciliani.jpg'),
(225,'Pignolata messinese','dolce','225_pignolata_messinese.jpg'),
(226,'Pappa al pomodoro','primo','226_pappa_al_pomodoro.jpg'),
(227,'Ribollita toscana','primo','227_ribollita_toscana.jpg'),
(228,'Bistecca alla fiorentina','secondo','228_bistecca_alla_fiorentina.jpg'),
(229,'Panzanella toscana','contorno','229_panzanella_toscana.jpg'),
(230,'Cacciucco livornese','secondo','230_cacciucco_livornese.jpg'),
(231,'Peposo all’imprunetina','secondo','231_peposo_allimprunetina.jpg'),
(232,'Lampredotto','secondo','232_lampredotto.jpg'),
(233,'Crostini toscani','antipasto','233_crostini_toscani.jpg'),
(234,'Acquacotta maremmana','primo','234_acquacotta_maremmana.jpg'),
(235,'Gnudi ricotta e spinaci','primo','235_gnudi_ricotta_e_spinaci.jpg'),
(236,'Cantucci toscani','dolce','236_cantucci_toscani.jpg'),
(237,'Castagnaccio','dolce','237_castagnaccio.jpg'),
(238,'Schiacciata all’uva','dolce','238_schiacciata_alluva.jpg'),
(239,'Torta co’ bischeri','dolce','239_torta_co_bischeri.jpg'),
(240,'Fagioli all’uccelletto','contorno','240_fagioli_alluccelletto.jpg'),
(241,'Canederli allo speck','primo','241_canederli_allo_speck.jpg'),
(242,'Spätzle agli spinaci','primo','242_spatzle_agli_spinaci.jpg'),
(243,'Strangolapreti trentini','primo','243_strangolapreti_trentini.jpg'),
(244,'Gulasch sudtirolese','secondo','244_gulasch_sudtirolese.jpg'),
(245,'Carne salada e fasoi','secondo','245_carne_salada_e_fasoi.jpg'),
(246,'Tortel di patate','contorno','246_tortel_di_patate.jpg'),
(247,'Polenta di Storo','primo','247_polenta_di_storo.jpg'),
(248,'Zuppa d’orzo tirolese','primo','248_zuppa_dorzo_tirolese.jpg'),
(249,'Schlutzkrapfen','primo','249_schlutzkrapfen.jpg'),
(250,'Crauti alla tirolese','contorno','250_crauti_alla_tirolese.jpg'),
(251,'Strudel di mele','dolce','251_strudel_di_mele.jpg'),
(252,'Krapfen tirolesi','dolce','252_krapfen_tirolesi.jpg'),
(253,'Zelten trentino','dolce','253_zelten_trentino.jpg'),
(254,'Strauben','dolce','254_strauben.jpg'),
(255,'Torta di grano saraceno','dolce','255_torta_di_grano_saraceno.jpg'),
(256,'Torta al testo','antipasto','256_torta_al_testo.jpg'),
(257,'Strangozzi al tartufo','primo','257_strangozzi_al_tartufo.jpg'),
(258,'Pasta alla norcina','primo','258_pasta_alla_norcina.jpg'),
(259,'Palomba alla ghiotta','secondo','259_palomba_alla_ghiotta.jpg'),
(260,'Agnello scottadito umbro','secondo','260_agnello_scottadito_umbro.jpg'),
(261,'Friccò all’eugubina','secondo','261_fricco_alleugubina.jpg'),
(262,'Bandiera umbra','contorno','262_bandiera_umbra.jpg'),
(263,'Fagiolina del Trasimeno','contorno','263_fagiolina_del_trasimeno.jpg'),
(264,'Crescia di Gubbio','antipasto','264_crescia_di_gubbio.jpg'),
(265,'Rocciata umbra','dolce','265_rocciata_umbra.jpg'),
(266,'Torcolo di San Costanzo','dolce','266_torcolo_di_san_costanzo.jpg'),
(267,'Pinoccate perugine','dolce','267_pinoccate_perugine.jpg'),
(268,'Tozzetti umbri','dolce','268_tozzetti_umbri.jpg'),
(269,'Zuppa di lenticchie di Castelluccio','primo','269_zuppa_di_lenticchie_di_castelluccio.jpg'),
(270,'Cipollata umbra','primo','270_cipollata_umbra.jpg'),
(271,'Fonduta valdostana','antipasto','271_fonduta_valdostana.jpg'),
(272,'Polenta concia valdostana','primo','272_polenta_concia_valdostana.jpg'),
(273,'Carbonade valdostana','secondo','273_carbonade_valdostana.jpg'),
(274,'Cotoletta alla valdostana','secondo','274_cotoletta_alla_valdostana.jpg'),
(275,'Seupa à la vapelenentse','primo','275_seupa_a_la_vapelenentse.jpg'),
(276,'Crespelle alla valdostana','primo','276_crespelle_alla_valdostana.jpg'),
(277,'Gnocchi alla bava','primo','277_gnocchi_alla_bava.jpg'),
(278,'Trota alla valdostana','secondo','278_trota_alla_valdostana.jpg'),
(279,'Civet di camoscio','secondo','279_civet_di_camoscio.jpg'),
(280,'Tegole valdostane','dolce','280_tegole_valdostane.jpg'),
(281,'Fiandolein','dolce','illustrazione_281_fiandolein_v3.svg'),
(282,'Mecoulin di Cogne','dolce','282_mecoulin_di_cogne.jpg'),
(283,'Torta di pere e cioccolato','dolce','283_torta_di_pere_e_cioccolato.jpg'),
(284,'Frittelle di mele valdostane','dolce','284_frittelle_di_mele_valdostane.jpg'),
(285,'Zuppa di castagne valdostana','primo','285_zuppa_di_castagne_valdostana.jpg'),
(286,'Baccalà alla vicentina','secondo','286_baccala_alla_vicentina.jpg'),
(287,'Risi e bisi','primo','287_risi_e_bisi.jpg'),
(288,'Bigoli in salsa','primo','288_bigoli_in_salsa.jpg'),
(289,'Sarde in saor','antipasto','289_sarde_in_saor.jpg'),
(290,'Fegato alla veneziana','secondo','290_fegato_alla_veneziana.jpg'),
(291,'Pasta e fasoi veneta','primo','291_pasta_e_fasoi_veneta.jpg'),
(292,'Risotto al radicchio','primo','292_risotto_al_radicchio.jpg'),
(293,'Polenta e schie','secondo','293_polenta_e_schie.jpg'),
(294,'Seppie al nero','secondo','294_seppie_al_nero.jpg'),
(295,'Baccalà mantecato','antipasto','295_baccala_mantecato.jpg'),
(296,'Tiramisù','dolce','296_tiramisu.jpg'),
(297,'Pandoro veronese','dolce','297_pandoro_veronese.jpg'),
(298,'Zaleti veneziani','dolce','298_zaleti_veneziani.jpg'),
(299,'Fritole veneziane','dolce','299_fritole_veneziane.jpg'),
(300,'Pearà veronese','contorno','300_peara_veronese.jpg');
